import BackGroundBlur from "@/components/background-blur";
import clsx from "clsx";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const font = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={clsx(font.className)}>
        {<BackGroundBlur />}
        <div className="fixed inset-0 flex justify-center backdrop-blur-2xl sm:px-8">
          <div className="flex w-full max-w-7xl lg:px-8">
            <div className="w-full bg-zinc-900/80 ring-1 ring-zinc-300/20"></div>
          </div>
        </div>
        <main className="relative mx-auto flex min-h-screen max-w-7xl flex-col items-center p-8 lg:p-24">
          {children}
        </main>
      </body>
    </html>
  );
}
